### ISSUE TITLE
Avoid JDOODLE

### ISSUE THREAD

**Issue by thecodersatish** [DhruvGheewala/Decoder#97]
Bro, Please avoid jdoodle api and provide code for java and c++ also

**Comment by kushalp13** [comment]
Hi there, 
We are currently working on building dockerize container for compiling all programming languages at the same place without depending on external support. As of now the requests for Compiling Java and C++ is limited to 200 requests per day while other programming languages has unlimited requests. We'll soon be releasing the next update. Thanks for your suggestion! 
- 
_Team Decoder_
